language: java

addons:
  apt:
    packages:
    - sshpass

jdk:
  - openjdk8

cache:
  directories:
  - '$HOME/.m2/repository'

script:
  - cd acm-commons-utils
  - mvn package -DskipTests=true
  - mvn install:install-file
    -Dfile=target/acm-commons-utils-1.0.jar
    -DgroupId=team.huoguo
    -DartifactId=acm-commons-utils -Dversion=1.0 -Dpackaging=jar
  - cd ..
  - cd acm-commons-controller
  - mvn package -DskipTests=true
  - mvn install:install-file
      -Dfile=target/acm-commons-controller-1.0.jar
      -DgroupId=team.huoguo
      -DartifactId=acm-commons-controller -Dversion=1.0 -Dpackaging=jar
  - cd ..
  - cd acm-gateway
  - mvn package -DskipTests=true
  - cd target
  - cp ../../dockerfile .
  - echo 'COPY acm-gateway-1.0.jar /app/' >> dockerfile
  - echo 'CMD java -jar /app/acm-gateway-1.0.jar' >> dockerfile
  - sshpass -p ${gatewaypwd} ssh -o StrictHostKeyChecking=no root@${gatewayip} 'docker stop gateway'
  - sshpass -p ${gatewaypwd} ssh -o StrictHostKeyChecking=no root@${gatewayip} 'docker rm gateway'
  - sshpass -p ${gatewaypwd} ssh -o StrictHostKeyChecking=no root@${gatewayip} 'docker rmi gateway'
  - sshpass -p ${gatewaypwd} ssh -o StrictHostKeyChecking=no root@${gatewayip} 'mkdir /root/gateway'
  - sshpass -p ${gatewaypwd} scp acm-gateway-1.0.jar dockerfile root@${gatewayip}:/root/gateway
  - sshpass -p ${gatewaypwd} ssh -o StrictHostKeyChecking=no root@${gatewayip} 'docker build -t gateway /root/gateway'
  - sshpass -p ${gatewaypwd} ssh -o StrictHostKeyChecking=no root@${gatewayip} 'docker run -d --network host --restart=always --name gateway gateway'

after_success:
  - ls -lt

branches:
  only:
    - master

notifications:
  email: false

env:
  global:
  - GH_REF=https://github.com/GreenHatHG/ACMRecentContests_SpringCloudAlibaba.git
