language: java

jdk:
  - openjdk8

cache:
  directories:
  - '$HOME/.m2/repository'

script:
  - cd acm-commons-utils
  - mvn package -DskipTests=true
  - mvn install:install-file
    -Dfile=target/acm-commons-utils-1.0.jar
    -DgroupId=team.huoguo
    -DartifactId=acm-commons-utils -Dversion=1.0 -Dpackaging=jar
  - cd ..
  - cd acm-commons-controller
  - mvn package -DskipTests=true
  - mvn install:install-file
      -Dfile=target/acm-commons-controller-1.0.jar
      -DgroupId=team.huoguo
      -DartifactId=acm-commons-controller -Dversion=1.0 -Dpackaging=jar
  - cd ..
  - cd acm-gateway
  - mvn package -DskipTests=true
  - cd target
  - wget https://github.com/timvisee/ffsend/releases/download/v0.2.55/ffsend-v0.2.55-linux-x64-static
  - mv ./ffsend-* ./ffsend
  - chmod a+x ./ffsend
  - ./ffsend upload acm-gateway-1.0.jar

after_success:
  - ls -lt

branches:
  only:
    - master

notifications:
  email: false

env:
  global:
  - GH_REF=https://github.com/GreenHatHG/ACMRecentContests_SpringCloudAlibaba.git
