language: java

jdk:
  - openjdk8

cache:
  directories:
  - '$HOME/.m2/repository'

script:
  - cd acm-commons-utils
  - mvn package -DskipTests=true
  - mvn install:install-file
    -Dfile=target/acm-commons-utils-1.0.jar
    -DgroupId=team.huoguo
    -DartifactId=acm-commons-utils -Dversion=1.0 -Dpackaging=jar
  - cd ..
  - cd acm-commons-controller
  - mvn package -DskipTests=true
  - mvn install:install-file
      -Dfile=target/acm-commons-controller-1.0.jar
      -DgroupId=team.huoguo
      -DartifactId=acm-commons-controller -Dversion=1.0 -Dpackaging=jar
  - cd ..
  - cd acm-gateway
  - mvn package -DskipTests=true
  - cd target
  - cp ../../dockerfile .
  - sed 'COPY acm-gateway-1.0.jar /app/' dockerfile
  - sed 'CMD java -jar /app/acm-gateway-1.0.jar' dockerfile
  - apt-get install sshpass scp -y

  - sshpass -p ${gate-pwd} scp acm-commons-controller-1.0.jar dockerfile root@{gateway-ip}:/root/gateway
  - sshpass -p ${gate-pwd} ssh -o StrictHostKeyChecking=no root@${gateway-ip} 'docker build -t gateway /root/gateway'
  - sshpass -p ${gate-pwd} ssh -o StrictHostKeyChecking=no root@${gateway-ip} 'docker run -d gateway --network host --restart=always --name gateway gateway'

after_success:
  - ls -lt

branches:
  only:
    - master

notifications:
  email: false

env:
  global:
  - GH_REF=https://github.com/GreenHatHG/ACMRecentContests_SpringCloudAlibaba.git
