FROM openjdk:8-alpine
RUN mkdir /app
COPY acm-service-userinfo/target/acm-service-userinfo-1.0.jar  /app/
CMD java -jar /app/acm-service-userinfo-1.0.jar
FROM openjdk:8-alpine
RUN mkdir /app
COPY acm-service-userinfo/target/acm-service-userinfo-1.0.jar  /app/
CMD java -jar /app/acm-service-userinfo-1.0.jar
