FROM openjdk:8-alpine
RUN mkdir /app
COPY acm-service-remind/target/acm-service-remind-1.0.jar  /app/
CMD java -jar /app/acm-service-remind-1.0.jar
FROM openjdk:8-alpine
RUN mkdir /app
COPY acm-service-remind/target/acm-service-remind-1.0.jar  /app/
CMD java -jar /app/acm-service-remind-1.0.jar
